### PR TITLE
Add initial support for Mermaid

### LINKED ISSUE #72: Mermaid support
Request to add support for mermaid diagrams. 

UseCase: Take GitHub markdown with Mermaid diagrams and convert it to LaTeX for document generation.

### PR DESCRIPTION
**Pull request by SanchayanMaity**
Closes #72.

### CODE REVIEW

**Comment by LaurentRDC** [comment]
Thank you for your submission! P

lease make sure the warning above is taken care of.

I updated the configuration for CI; please merge the master branch so that we may see what CI has to say about this pull request.

**Comment by SanchayanMaity** [comment]
Have fixed the warning and rebased the PR on top of master branch.

**Comment by LaurentRDC** [comment]
Awesome, thank you! I will prepare a release today

**Comment by maurerle** [comment]
Is there any documentation on this issue? Seems like this is missing in readme.md and manual-content.md and there does not exist any example?

It did not work for me despite having mmdc installed using:

    # Mermaid test
    
    ```{.mermaid}
    sequenceDiagram
        Alice->John: Hello John, how are you?
        John->Alice: Great!
    ```

Though the problem is that this package is not yet available in conda: https://anaconda.org/conda-forge/pandoc-plot

**Comment by LaurentRDC** [comment]
@maurerle You can check what toolkits are available in your installation using `pandoc-plot toolkits`. For example, on my current machine:

```bash
$ pandoc-plot toolkits

AVAILABLE TOOLKITS

Toolkit: Asymptote
    Executable: asy
    Code block trigger: asy
    Supported save formats: PDF, EPS, PNG


UNAVAILABLE TOOLKITS

Toolkit: Python/Matplotlib
    Code block trigger: matplotlib
    Supported save formats: PNG, PDF, SVG, JPG, EPS, TIF

... (many more) ...

Toolkit: Mermaid
    Code block trigger: mermaid
    Supported save formats: PDF, PNG, SVG
```

There could be two situations:

1. Mermaid isn't configured/installed on your machine, in which case you'll see that the toolkit is unavailable (like in the example above);
2. Your installation of `pandoc-plot` isn't recent enough, in which case `pandoc-plot toolkits` won't even mention Mermaid.

As you mention, the [latest version available in `conda`](https://anaconda.org/conda-forge/pandoc-plot) is not recent enough, so that might be your problem. I'll try to deploy the latest version in `conda` right now.

**Comment by LaurentRDC** [comment]
Packaging executables is a major pain with conda-forge; I wasn`t able to create a new version.

Your best bet is therefore to use one of the executables provided in [releases](https://github.com/LaurentRDC/pandoc-plot/releases/tag/1.9.1).

**Comment by reagle** [comment]
Mermaid should be added to the README https://github.com/LaurentRDC/pandoc-plot?tab=readme-ov-file#supported-toolkits

**Comment by LaurentRDC** [comment]
Thanks @reagle for the reminder! Done in f9bff4bfb1e186fa81ecf348d70c3a31f8c61638

**Pull request merged**
